<div class="topmaincont pad10">
<table style="width:100%;"><tr><td class="width150 valigntop">
    <div id="menu" class="floatleft">
    <?php echo $this->menu; ?>
    </div>
</td>
                              <td class="valigntop">
    <div id="usercpcontent">
                   <h1>News</h1>
                   <div class="line"></div>
                   <h5>You can add or delete news using the forms below. If the date of the news submitted already existed in the database,
                                  the new entry will replace the old entry.</h5><br/>

                                  Date:<br/><input type="text" id="newsdate" name="newdate" class="rounded3" /><br/>
                                  Heading: <br/><input type="text" id="newsheading" name="newsheading" class="rounded3" /><br/>
                                  Content: <br/><textarea id="newscontent" name="newscontent" cols="40" rows="5" class="rounded3"></textarea><br/>
                                  <a id="submitnews" class="btn">Submit news</a>

                                  <br/><br/><br/>
                                  <h2 class="textright">Previous news entries</h2>
                                   <?php foreach($this->newslist as $newslist) : ?>
                                             <div>
                                                            <div class="line"></div>
                                                            <span class="newshead"><?php echo $newslist["heading"] ?></span> <span class="newsdate"><?php echo $newslist["date"] ?></span>
                                                            <img src="/img/cross.png" alt="" class="removenews" id="rem<?php echo $newslist["newsid"] ?>"/>
                                                            <br/>
                                                            <?php echo $newslist["content"] ?>                                                            
                                             </div>
                                  
                               <?php endforeach; ?>


    </div>
 </td></tr></table><br/>
    <div class="clear"></div>
</div>
<div id="pagediv"></div>
