<div class="topmaincont textcenter">
               <div id="headimgnowrap">
               <img src="/img/teamgb.gif" alt="" class="valignmiddle" />
                <img src="/img/head.gif" alt="" class="valignmiddle" />
               <img src="/img/wcl.gif" alt="" class="valignmiddle" />
               </div>
               <form id="loginform" method="POST" action="/auth/forgotpass">
               <h1>I've forgotten my password!</h1><br/>
               Please input the email you used to register.<br/>
               Email: <input id="forgotemail" type="text" name="forgotemail"/><br/><br/>
               <input type="submit" value="Send me my password." id="forgotbutton"/><br/><br/><br/>
               </form>

</div>

<div id="pagediv"></div>
