<div class="topmaincont textcenter">
               <div id="headimgnowrap">
               <!--img src="/img/teamgb.gif" alt="" class="valignmiddle" /-->
                <img src="/img/head.gif" alt="" class="valignmiddle" />
               <img src="/img/wcl.gif" alt="" class="valignmiddle" />
               </div><br/>
	    <?php echo $this->form;  ?>
	<br/>
	<span style="color:#ffae00;">If you forgot your password, please <a href="/auth/forgotpass" style="color:#ff1e00;">click here</a>. If you do not have an account yet,
        <a href="/auth/register" style="color:#ff1e00;">please register.</a></span>
	<br/><br/>
</div>

<div id="pagediv"></div>
