<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                                  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
                                  <head>
                                  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
                                  <title>Print Plan</title>
                                  <!-- break --><style>
                                                            #printcontainer{
                                                                           font-family: \'Trebuchet MS\', sans-serif;
                                                                           font-style:italic;
                                                                           font-size:10px;
                                                            }

                                                            #printcontainer .date{
                                                                           font-weight: bold;
                                                            }


                                                            #printcontainer .exid{
                                                                           font-weight: bold;
                                                                           font-size: 17px;
                                                                           color:#000000;
                                                                            border-right:4px solid;
                                                            }

                                                            #printcontainer table{
                                                                           border:2px solid #6b6b6b;
                                                                           width:100%;
                                                                           table-layout: fixed;
                                                                           border-collapse: collapse;
                                                                           margin-bottom:5px;
                                                            }

                                                            #printcontainer td{
                                                                           background-color: #f5f5f5;
                                                                           margin:0px;
                                                                           color:#454545;
                                                                           text-align: center;
                                                                           border-right: 1px solid #858585;
                                                                           border-bottom: 1px solid #858585;
                                                                           line-height:10px;
                                                                           padding:4px;
                                                            }


                                                            #printcontainer h2{
                                                                           border-bottom: 1px dotted #545454;
                                                            }
                                                            #printcontainer.red{
                                                                           color:#e44115;
                                                                           font-size:15px;
                                                            }
                                                            #printcontainer table .commentbox, #printcontainer .commentbox tr, #printcontainer .commentbox td{
                                                                           border:none;
                                                                           background:none;
                                                                           text-align:left;
                                                                           padding: 2px;
                                                            }
                                                            #printcontainer .commentbox{
                                                                           margin:5px;
                                                                           border:1px solid #c8c8c8 !important;
                                                                           padding:5px;
                                                                           height:40px;
                                                                           color:#585858;
                                                                           margin-bottom: 10px;
                                                                           line-height: 10px;
                                                                           vertical-align:top;
                                                              }

                                  </style><!-- break -->
                                  
                                  </head>
                                  <body>
                                                 <!-- break --><div id="printcontainer"> <!-- break -->
                                                 <img src="http://otd.naturallyartificial.net/img/smallwcl.gif" alt="" style="float:right;"/>
                                  <h2>Plan: <?php echo str_replace("\\","",$this->plan["planname"]); ?></h2>
                                  <span class="red">Please fill empty boxes with the applied KGs or strikethrough which were not done.</span>
                                  <!-- break -->
                                  <div id="print">

<?php
                                  error_reporting(E_ALL);
foreach($this->days as $day){
                              $commentblock = "";
                                  echo '<div class="date">&raquo; '.date("l d-M-Y", strtotime($day[0]["date"])).'</div>';
                                  echo '<table>
                                                 ';
                                  $exid = 0;
                                 $count = 0;
                                 $cells = 0;
                                foreach($day as $d){

                                               if($d["exerciseid"] != $exid){
                                                              $exid = $d["exerciseid"];
                                                              if($count == 0){
                                                              echo '<tr><td class="exid">'.$d["exerciseid"].'</td>
                                                                                            ';
                                                              $count += 1;
                                                              }
                                                              else{
                                                                             if($this->cellsperrow > $cells){
                                                                                            for($ii=0;$ii < ($this->cellsperrow - $cells); $ii++){
                                                                                                           echo '<td></td>';
                                                                                            }
                                                                                            $cells = 0;
                                                                             }
                                                                               echo '</tr><tr><td class="exid">'.$d["exerciseid"].'</td>
                                                                                              ';
                                                              }
                                               }
                                               //normal mode
                                             /*echo '<td>'.$d["weight"].'/'.$d["reps"].'/'.$d["sets"].'</td>
                                                              ';
                                                             $cells++;
                                              */
                                               //or separated mode
                                               for($i=0;$i<$d["sets"];$i++){
                                                              echo '<td>'.$d["weight"].'/'.$d["reps"].'<br/></td>
                                                            ';
                                                              if($d["comment"]){
                                                                             $str = 'for ' . $this->exercisearray[$d["exerciseid"]] . ' ('.$d["weight"].'/'.$d["reps"].') - ';
                                                                             if(stristr($commentblock, $str) == false){
                                                                                          $commentblock  .= $str . str_replace("\\","",$d["comment"]) . '<br/>';
                                                                             }
                                                              }
                                                              $cells++;
                                               }
                                               //end modes

                                }
                                if($this->cellsperrow > $cells){
                                                                                            for($ii=0;$ii < ($this->cellsperrow - $cells); $ii++){
                                                                                                           echo '<td></td>';
                                                                                            }
                                                                                            $cells = 0;
                                                                             }

                                echo '</tr>
                                               </table>
                                                            <table class="commentbox">
                                                                           <tr>
                                                                                          <td style="width:200px;">
                                                                                                         Body weight: _______kg.<br/>
                                                                                                         Notes:
                                                                                          </td>
                                                                                          <td style="width:240px;">
                                                                                          Exercise intensity rating 0 - 10:_____<br/>
                                                                                          <span style="font-size:8px;">Please record within 30 min of finishing training)</span>
                                                                                          </td>
                                                                                          <td>
                                                                                          Coach Notes:
                                                                                          </td>
                                                                           </tr>
                                                                           <tr>
                                                                                           <td>
                                                                                          </td>
                                                                                          <td>
                                                                                          </td>
                                                                                          <td>
                                                                                          <span class="commentblock">'.$commentblock.'</span>
                                                                                          </td>
                                                                           </tr>
                                                            </table>

                                             ';
                   }
?>

                                                 </div></div><!-- break --></body></html>