<div class="topmaincont pad10">
<table style="width:100%;"><tr><td class="width150 valigntop">
    <div id="menu" class="floatleft">
    <?php echo $this->menu; ?>
    </div>
 </td> <td class="valigntop">
    <div id="usercpcontent">
<input type="hidden" value="" id="userid" />
<h1>Athlete Analysis</h1>
<div class="line"></div>
<fieldset>
               <legend>Select an athlete</legend>
               <select id="athlete_graph_list">
                              <?php
                                             foreach($this->athletes as $athlete){
                                                            echo '<option value="'.$athlete["athleteid"].'">'.$athlete["name"].' '.$athlete["surname"].'</option>';
                                             }
                              ?>
               </select>
               <a id="setathleteid">Display graphs for this athlete</a>
               &nbsp;&nbsp;&nbsp;&raquo; When switching between athletes, please allow a few seconds for the system to re-draw the graphs
</fieldset>
<div id="hidegraphsection">
               <fieldset><legend>Show/Hide graphs</legend>
               <button id="openallgraph">Show all graphs</button>
               <button id="closeallgraph">Hide all graphs</button><br/>
               <button id="gd_trainingload_btn" class="graphbtn">Training Load</button>
               <button id="gd_totalload_btn" class="graphbtn">Total Load</button>
               <button id="gd_totalloaddaily_btn" class="graphbtn">Total Load (Daily)</button>
               <!--<button id="gd_ratio_btn" class="graphbtn">S/W Ratio</button>-->
               <button id="gd_totalreps_btn" class="graphbtn">Total Reps</button>
               <!--<button id="gd_monotony_btn" class="graphbtn">Monotony & Strain</button>-->
               <button id="gd_fatigue_btn" class="graphbtn">Fatigue & Recovery</button>
               <button id="gd_sleepquantity_btn" class="graphbtn">Sleep quantity</button>
               <button id="gd_movement_btn" class="graphbtn">Movement</button>
               <button id="gd_movementpl_btn" class="graphbtn">Movement (PL)</button>
               <button id="gd_weighthydration_btn" class="graphbtn">Body weight & Hydr.</button>
               </fieldset>
                  <div class="graphdiv hide" id="gd_trainingload">
               <h3>Training Load</h3>
              <?php echo ' <img src="" alt="" id="chart0" />'; ?>
               
                <div class="graph">
                                  <table>
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph0_startdate" name="grapho_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph0_enddate" name="graph0_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph0_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph0_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>


                   </div>
                  </div>

<!-- <div class="graphdiv">
               <h3>Total Weight Lifted</h3>

                                                                <?php   echo '<img src="" alt="" id="chart1" />   ';                ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph1_startdate" name="graph1_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph1_enddate" name="graph1_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph1_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph1_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
                                             </div>-->
<div class="graphdiv hide" id="gd_totalload">
               <h3>Total Load / Average Load</h3>
                <?php   echo '<img src="'.$this->images[1].'" alt="" id="chart5" />   '; ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                              <!--  <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph5_startdate" name="graph5_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph5_enddate" name="graph5_enddate" class="rounded3"/>
                                                                               </fieldset> -->
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph5_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph5_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

<div class="graphdiv hide" id="gd_totalloaddaily">
               <h3>Total Load / Average Load</h3>
                <?php   echo '<img src="" alt="" id="chart30" />   '; ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph30_startdate" name="graph30_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph30_enddate" name="graph30_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph30_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph30_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

<!--<div class="graphdiv hide" id="gd_ratio">
               <h3>Strength / Weight Ratio</h3>
                <?php   echo '<img src="" alt="" id="chart8" />   ';    ?>
                <table class="graph">
                                                 <tr>
                                                                <td>

                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph8_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph8_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div> -->
<div class="graphdiv hide" id="gd_totalreps">
               <h3>Total Reps Done</h3>
               <?php   echo '<img src="" alt="" id="chart3" />   '; ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph3_startdate" name="graph3_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph3_enddate" name="graph3_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph3_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph3_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
                                             </div>
<!--<div class="graphdiv hide" id="gd_monotony">
               <h3>Monotony & Strain</h3>
               <?php   echo '<img src="" alt="" id="chart6" />   ';                ?>
                <table class="graph">
                                                 <tr>
                                                                <td>

                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph6_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph6_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>-->
<div class="graphdiv hide" id="gd_fatigue">
               <h3>Fatigue and Recovery</h3>
                <?php   echo '<img src="'.$this->images[2].'" alt="" id="chart2" />   '; ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph2_startdate" name="graph2_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph2_enddate" name="graph2_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph2_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph2_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                                 <tr>
                                                                <td colspan="3">
                                                                               <fieldset>
                                                                                              <legend>Include in graph</legend>
                                                                                              <label id="cb1"> <input type="checkbox" id="sq" checked="checked">Sleep quality</label>
                                                                                              <label id="cb2"> <input type="checkbox" id="mr" checked="checked">Mental Recovery</label>
                                                                                              <label id="cb3"> <input type="checkbox" id="pr" checked="checked">Physical Recovery</label><br/>
                                                                                              <label id="cb4"> <input type="checkbox" id="pte" checked="checked">Pre Training Energy</label>
                                                                                              <label id="cb5"> <input type="checkbox" id="ms" checked="checked">Muscle Soreness</label>
                                                                                              <label id="cb6"> <input type="checkbox" id="gf" checked="checked">General Fatigue</label>
                                                                               </fieldset>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

<div class="graphdiv hide" id="gd_sleepquantity">
               <h3>Sleep quantity</h3>
               <?php   echo '<img src="" alt="" id="chart7" />   ';       ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph7_startdate" name="graph7_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph7_enddate" name="graph7_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph7_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph7_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

 <div class="graphdiv hide" id="gd_movement">
               <h3>Weight/Movement</h3>
                <?php   echo '<img src="" alt="" id="chart9" />   '; ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset id="movementgraphparams">
                                                                                              <legend>Include in graph</legend>
                                                                                              <label id="mcb1"> <input type="checkbox" id="snatch" checked="checked">Snatch</label>
                                                                                              <label id="mcb2"> <input type="checkbox" id="psnatch" checked="checked">Power Snatch</label>
                                                                                              <label id="mcb3"> <input type="checkbox" id="cj" checked="checked">Clean & Jerk</label><br/>
                                                                                              <label id="mcb4"> <input type="checkbox" id="pc" checked="checked">Power Clean</label>
                                                                                              <label id="mcb5"> <input type="checkbox" id="squat" checked="checked">Squat</label>
                                                                                              <label id="mcb6"> <input type="checkbox" id="pjfr" checked="checked">Power Jerk (from racks)</label>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph9_limit" title="Maximum number of days displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph9_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

<div class="graphdiv hide" id="gd_movementpl">
               <h3>Weight/Movement (PL)</h3>
                <?php   echo '<img src="" alt="" id="chart90" />   '; ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset id="movementplgraph">
                                                                                              <legend>Include in graph</legend>
                                                                                              <label id="mcb1"> <input type="checkbox" id="snatch" checked="checked">Holds</label>
                                                                                              <label id="mcb2"> <input type="checkbox" id="psnatch" checked="checked">Doubles</label>
                                                                                              <label id="mcb3"> <input type="checkbox" id="cj" checked="checked">Jamaican Press</label><br/>
                                                                                              <label id="mcb4"> <input type="checkbox" id="pc" checked="checked">Board Press</label>
                                                                                              <label id="mcb5"> <input type="checkbox" id="squat" checked="checked">Bottoms</label>
                                                                                              
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph90_limit" title="Maximum number of days displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph90_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

 <div class="graphdiv hide" id="gd_weighthydration">
               <h3>Body weight & Hydration</h3>
               <?php   echo '<img src="" alt="" id="chart20" />   ';                ?>
                <table class="graph">
                                                 <tr>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Date Range</legend>

                                                                                              Start: <input type="text" id="graph20_startdate" name="graph2_startdate" class="rounded3"/>
                                                                                          End: <input type="text" id="graph20_enddate" name="graph2_enddate" class="rounded3"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <fieldset class="rounded3">
                                                                                              <legend>Display limit</legend>
                                                                                              <input type="text" id="graph20_limit" title="Maximum number of date displayed on X-axis" class="rounded3" value="10"/>
                                                                               </fieldset>
                                                                </td>
                                                                <td>
                                                                               <a id="setgraph20_params">Reload Graph &raquo;</a>
                                                                </td>
                                                 </tr>
                                                 <tr>
                                                                <td colspan="3">
                                                                               <fieldset>
                                                                                              <legend>Include in graph</legend>
                                                                                              <label id="wh1"> <input type="checkbox" id="bwm" checked="checked" class="bh">Body weight (Morning)</label>
                                                                                              <label id="wh2"> <input type="checkbox" id="bwe" checked="checked" class="bh">Body weight (Evening)</label>
                                                                                              <label id="wh3"> <input type="checkbox" id="um" checked="checked" class="bh">Urine (Morning)</label><br/>
                                                                                              <label id="wh4"> <input type="checkbox" id="ue" checked="checked" class="bh">Urine (Evening)</label>
                                                                               </fieldset>
                                                                </td>
                                                 </tr>
                                  </table>
 </div>

</div>
<div class="line"></div><div class="line"></div>
<h3>Corelation Graphs</h3>

<img src="/chart/index/mode/drawchart_correlation/type/SS" id ="colgraph" alt=""/><br/>
<a class="viewSCJ btn">Squat vs C&J</a> <a class="viewSSS btn">Squat vs Snatch</a> <a class="viewData btn">View Data Table</a>
<div id="datatable"></div>
    </div>

           



    <div class="clear"></div>
    </td></tr></table>
</div>
<div id="pagediv"></div>

